### ISSUE TITLE
Rdio deprecating OAuth 1.0 causes this to no longer work

### ISSUE THREAD

**Issue by cdl** [MattMur/rdio-spotify-artistfollow#1]
Looks like this no longer works, as Rdio no longer supports OAuth 1.0. Trying to launch this shows the following error from Rdio:

```
Oops!

OAuth 1.0 has been disabled, see the developer blog for details:
http://blog.rdio.com/developers/2015/06/oauth-20-launch.html
```

**Comment by forivall** [comment]
@cdl: my pr should fix this. However, I also updated it so that it automatically follows all of the artists too, so some forewarning there. You can just checkout my "no-auto" branch on my fork if you don't want that to happen.
